output "cognitive_account_name" {
  description = "The name of the Cognitive Account"
  value       = azurerm_cognitive_account.this.name
}

output "cognitive_account_endpoint" {
  description = "The endpoint of the Cognitive Account"
  value       = azurerm_cognitive_account.this.endpoint
}

output "project_name" {
  description = "The name of the AI Foundry project"
  value       = azurerm_cognitive_account_project.project.name
}

output "project_endpoint" {
  description = "The endpoint for the AI Foundry project"
  value       = "https://${azurerm_cognitive_account.this.custom_subdomain_name}.services.ai.azure.com/api/projects/${azurerm_cognitive_account_project.project.name}"
}

# # Generate .env file for Python scripts
# resource "local_file" "env_file" {
#   filename = "${path.module}/../../.env"
#   content  = <<-EOT
# # Auto-generated by Terraform - do not edit manually
# # Generated from infra/project

# # Azure AI Foundry Configuration
# AZURE_SUBSCRIPTION_ID=${data.azurerm_client_config.current.subscription_id}
# AZURE_RESOURCE_GROUP=${var.resource_group_name}
# AZURE_AI_ACCOUNT_NAME=${azurerm_cognitive_account.this.custom_subdomain_name}
# AZURE_AI_PROJECT_NAME=${azurerm_cognitive_account_project.project.name}
# AZURE_AI_PROJECT_ENDPOINT=https://${azurerm_cognitive_account.this.custom_subdomain_name}.services.ai.azure.com/api/projects/${azurerm_cognitive_account_project.project.name}

# # Agent Configuration
# AGENT_NAME=APIMGatewayAgent
# AGENT_MODEL=model-gateway/gpt-4o-mini
# EOT
# }
